<div class="s-prose s-prose__disable-spoiler-hover js-post-body" itemprop="text">
<p>The most suspicious thing to me is this:</p>

<pre><code>except ValueError:
    pass
</code></pre>

<p>It's on a very broad <code>try</code> block, which leads me to believe that it was thrown in to attempt a pseudo fail-safe loop. Fail-safe loops are not a bad thing, but this isn't a great way to go about it. Contrary to most circumstances, it's actually a good idea here to broaden your caught exception class to <code>Exception</code>, so long as you output the error before continuing with the loop.</p>

<p>I'll also say: if <code>ValueError</code> is produced by a condition that you know and understand, try to check for that condition before it raises an exception, print a message and continue. And/or - if you understand the source line of this common exception but aren't able to check for failure conditions beforehand, apply a narrower try/catch to only that line, again emitting a sane message and continuing on with your loop.</p>
    </div>